#!/bin/bash

# For more information regarding bash shells, see:
# https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files

#
# This script is sourced before '/usr/share/entrypoint.sh'
# Look in '/usr/share/entrypoint.sh' for examples of setting
# environment variables in the environment immediately
# after entering the container
# 

echo
echo "Welcome $(whoami), from '/etc/bashrc'"
echo "Sourced by: $0."
echo

# colorized pretty print "username pwd $ "
export PS1='\[\e]0;\u \w\a\]\[\033[01;32m\]\u \[\033[01;34m\]\w \$\[\033[00m\] '

# See: https://unix.stackexchange.com/q/26676
[[ $- == *i* ]] \
    && echo 'This is an interactive shell' \
    || echo 'This is not an interactive shell'

# See: https://unix.stackexchange.com/q/26676
shopt -q login_shell \
    && echo 'This is a login shell' \
    || echo 'This is not a login shell'

echo 
